#!/bin/bash
echo "petle 4.1-6,9"

read -p "n = " n
#read -p "a = " a

#1
: '
for (( i = 1; i <= $n; i = i + 2 ))
do 
echo "$i"
done
'
#2
: '
if (( $a%2 == 0))
then
for (( i = $a; i <= $n; i = i + 2 ))
do 
echo "$i"
done
else
for (( i = $a + 1; i <= $n; i = i + 2 ))
do 
echo "$i"
done
fi
'
#3
: '
for (( i = 1; i <= $n; i = i + 2 ))
do 
echo "$i * $[ i + 1 ] = $[i * ( i + 1 )]"
done
'
#4
: '
for (( i = $a; i <= $n; i = i + 1 ))
do 
echo "$i	$[n +1 - i]"
done
'
#5
: '
if (( $a%3 == 0 )) 
then
	for (( i = $a; i <= $n; i = i + 3 )) 
	do
		echo "$i * $i = $[ i ** 2 ]"
	done
elif (( $a%3 == 1 ))
then
	for (( i = $a + 2; i <= $n; i = i + 3 )) 
	do
		echo "$i * $i = $[ i ** 2 ]"
	done
else
	for (( i = $a + 1; i <= $n; i = i + 3 )) 
	do
		echo "$i * $i = $[ i ** 2 ]"
	done
fi
'
#6
: '
read -p "a = " a
until (( $a == 0 ))
do
echo $a >> index
read -p "a = " a
done
echo " 0 konczy zapis"
'
#9
read -p "a = " a
for (( i = 0; i <= $n; i = i + 1 ))
do
w=$a
read -p "a = " a 
if (( $a > $w ))
then
w=$a
echo " liczba byla wieksza"
elif (( $w ==$a ))
then
echo " liczby sa rowne"
else
echo " liczba byla mniejsza"
fi 
done





