#!/bin/bash
echo "Wyświetlanie nazw dni tygodnia z wykorzystaniem pętli for"
dni_tygodnia="poniedzialek wtorek środa czwartek piątek sobota niedziela"

#Zmiennym, które są wykorzystywane do określania ilości "powtórzeń" pętli zwyczajowo nadaje się nazwy i, j lub k
for i in $dni_tygodnia
do 
#W pętli for podobnie jak w instrukcji warunkowej stosuje się wcięcia
echo "$i to $d dzien tygodnia"
done
