#!/bin/bash
echo "1.11-12"
#11
: '
echo "Sprawdzanie czy liczba jest podzielna/4."
read -p "a = " a
if (($a%4 == 0))
then
echo "a jest podzielne przez 4" 
else
echo "a nie jest podzielne przez 4"
fi
'
#12
: '
echo "Sprawdzanie czy liczba jest większa od 0, a mniejsza od 11."
read -p "a = " a
if [ $a -gt 0 -a $a -lt 11 ]
then
echo "a jest w zakresie" 
else
echo "a jest poza zakresem"
fi
'

