#!/bin/bash
echo "Program suma dwoch tablic"
#n=${#tablica[*]}
read -p "wielkosc tablic = " n
j=0
while [ $j -lt $n ]
do
read -p "podaj $j liczbe w tablicy = " a
tablica1[$j]=$a
j=$[j + 1] 
done
j=0
while [ $j -lt $n ]
do
read -p "podaj $j liczbe w tablicy = " a
tablica2[$j]=$a
j=$[j + 1] 
done
i=0
while [ $i -lt $n ]
do
tablica3[$i]=$[tablica1[i] + tablica2[i]]
i=$[i + 1]
done
echo "${#tablica[*]}"
