#!/bin/bash
echo "Program obliczający iloczyn elementów tablicy"
#n=${#tablica[*]}
read -p "wielkosc tablicy = " n
j=0
while [ $j -lt $n ]
do
read -p "podaj $j liczbe w tablicy = " a
tablica[$j]=$a
j=$[j + 1] 
done
s=1
i=0
while [ $i -lt $n ]
do
s=$[s * tablica[i]]
i=$[i + 1]
done
echo "Iloczyn elementów tablicy wynosi $s"
