#!/bin/bash
echo "Program obliczający sumę elementów o indeksach parzystych tablicy"
#n=${#tablica[*]}
read -p "wielkosc tablicy = " n
j=0
while [ $j -lt $n ]
do
read -p "podaj $j liczbe w tablicy = " a
tablica[$j]=$a
j=$[j + 1] 
done
s=0
i=0
# dla nieparzystych i=1
while [ $i -lt $n ]
do
s=$[s + tablica[i]]
i=$[i + 2]
done
echo "Suma elementów tablicy wynosi $s"
