#!/bin/bash
echo "Program obliczający liczbę wystąpień zadanego znaku w zmiennej tekstowej"
read -p "Podaj tekst " str
read -p "Podaj znak " char
n=${#str}
licznik=0
i=0
while [ $i -lt $n ]
do
if [ "${str:$i:1}" = $char ]
then
licznik=$[licznik + 1]
fi
i=$[i + 1]
done
echo "Liczba wystąpień znaku $char wynosi $licznik"
