#!/bin/bash
echo "iloczyn liczb podawanych przez użytkownika"
echo "Podaj ilość liczb"
read -p "n = " n
if [ $n -ge 1 ]
then
i=1
m=1
while [ $i -le $n ]
do
read -p "Podaj liczbę nr $i = " a
m=$[m * a]
i=$[i + 1]
done
echo "ilczyn liczb wynosi $m"
else
echo "n < 1"
fi
